version: '3.7'
services:
  hyperf:
    image: $REGISTRY_URL/$PROJECT_NAME:test
    environment:
      - "APP_PROJECT=小程序服务端"
      - "APP_ENV=production"
    ports:
      - 9098:9098
      - 9099:9099
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
      update_config:
        parallelism: 2
        delay: 5s
        order: start-first
    networks:
      - network
    configs:
      - source: miniapp-config-2
        target: /opt/www/.env
configs:
  miniapp-config-2:
    external: true
networks:
  network:
    external: true
